name: "Build"
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Launch and test
        run: |
          cd image
          docker compose build
  release:
    needs:
      - build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Release
        run: |
          npm install
          npx semantic-release --branches main
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Log in to Docker Hub
        uses: docker/login-action@5f4866a30a54f16a52d2ecb4a3898e9e424939cf
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Retrieve version
        id: tag  
        run: echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
      - name: Extract metadata (tags, labels)
        id: meta1
        uses: docker/metadata-action@1294d94f8ee362ab42b6da04c35f4cd03a0e6af7
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}
          tags: |
            ${{steps.tag.outputs.version}}
            latest
      - name: Build and push
        uses: docker/build-push-action@7e6f77677b7892794c8852c6e3773c3e9bc3129a
        with:
          context: ./image
          push: true
          tags: ${{ steps.meta1.outputs.tags }}
          labels: ${{ steps.meta1.outputs.labels }}