name: "Build"
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Launch and test
        run: |
          cd image
          docker compose up
  release:
    needs:
      - build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Install Node
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: package.json
      - name: Log in to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Release
        run: |
          npm install
          npx semantic-release --branches main
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
