name: "Build"
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Launch and test
        run: |
          cd image
          docker compose build
  release:
    needs:
      - build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Release
        run: |
          npm install
          npx semantic-release --branches main
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Log in to Docker Hub
        uses: docker/login-action@7840e6ddd4a9223910798f6a315544257fccd96e
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Retrieve version
        id: tag  
        run: echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
      - name: Extract metadata (tags, labels)
        id: meta1
        uses: docker/metadata-action@2ee3d3070bb41b40bf7305d15233321e12c1dc5c
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}
          tags: |
            ${{steps.tag.outputs.version}}
            latest
      - name: Build and push
        uses: docker/build-push-action@729f7f49266dec5e72fe7339273d3f7e65abacd7
        with:
          context: ./image
          push: true
          tags: ${{ steps.meta1.outputs.tags }}
          labels: ${{ steps.meta1.outputs.labels }}