project:
  output-dir: _site
format:
  revealjs: 
    theme: [white]
    slide-number: true
    html-math-method:
      method: mathjax   
    default-image-extension: ""
    controls-layout: bottom-right
    controls-tutorial: true
    preview-links: auto
    reference-location: document
    footnotes-hover: true
    scrollable: true
    width: 1100
