version: "3.9"
services:
  build-quarto:
    init: true
    # restart: always
    build:
      context: .
      dockerfile: Dockerfile
    hostname: build-quarto
    ports:
      - "6778:6778"
    container_name: build-quarto
    volumes:
      - ./:/data
    command: ["/bin/bash", "/data/build.sh"]